[package]
name = "test-auth"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
c2pa = { version = "0.7.0", features = ["file_io"] }
tempfile = "3.3.0"